### ISSUE TITLE
fade should not be applied on the first and last overlap

### ISSUE THREAD

**Issue by candlewill** [fatchord/WaveRNN#111]
I think the `fade_in` and `fade_out` should not be applied on the first and last overlap. The following code:

https://github.com/fatchord/WaveRNN/blob/b178948a031fa9f19e428956c71b3ce3ec5d2a3e/models/fatchord_version.py#L375

should be modified as:

```python
    first_overlap = y[0, :overlap]
    last_overlap = y[-1, -overlap:]
    y[:, :overlap] *= fade_in
    y[:, -overlap:] *= fade_out
    y[0, :overlap] = first_overlap
    y[-1, -overlap:] = last_overlap
```
@fatchord Do you think this is right?

**Comment by candlewill** [comment]
Another found in my experiment is that, the fading function `fade_in = np.sqrt(0.5 * (1 + t)); fade_out = np.sqrt(0.5 * (1 - t))` doesn't perform better than a simple linear function `fade_in = 0.5 * (1 + t); fade_out = 0.5 * (1 - t)`.

**Comment by fatchord** [comment]
@candlewill On the first comment - I've found that wavernn can be a little noisy when it's starting up so a fadein might be necessary. the fade in is around 10ms if I remember correctly - that's almost unnoticeable. The fade out is something I'm looking at since there can be clicks (caused by empty mel frames from the tts model).

As far as the second comment goes, I disagree - the rnn needs to warm up a little in my experience. Also a linear ramp will cause a small drop in perceived loudness. You can test this out by setting the overlap to a very long time and comparing my fade ramp vrs linear. You'll hear a much more pronounced tremelo effect with linear.

**Comment by candlewill** [comment]
Thanks.
