### ISSUE TITLE
What is the idea behind ```pad``` in collate function?

### ISSUE THREAD

**Issue by erogol** [fatchord/WaveRNN#24]
Could you please explain the ```pad``` variable and how it is helpful?

**Comment by fatchord** [comment]
@erogol The MelResNet part of the model has a 5 wide 1d convolution input - this needs to be padded to make the timesteps correct when upsampling and concatenating later on. 

I could have just used zero padding in the layer for this but it makes more sense to use the actual spectrogram data as padding instead. This also gives the model a 'peek' at what is coming up in the spectrogram instead of giving it zero convoluted noise.

I can see the confusion though - the pad=2 and the kernal_size=5 are all hardcoded. That needs to be refactored.

**Comment by erogol** [comment]
Thx for explaining it.
