### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by buscon** [fatchord/WaveRNN#45]
Hi,

I get a strange error when I launch the preprocess.py file.
The folder with my wav files is found and no other files are contained there.

How can I get through this error?

/WaveRNN$ python preprocess.py 

7690 wav files found in "/home/ubuntu/wav/"

Traceback (most recent call last):
  File "preprocess.py", line 52, in <module>
    text_dict = ljspeech(path)
  File "/home/ubuntu/WaveRNN/utils/text/recipes.py", line 9, in ljspeech
    assert len(csv_file) == 1
AssertionError

**Comment by fatchord** [comment]
@buscon Do you want to just train WaveRNN vocoder on its own?

**Comment by buscon** [comment]
correct, I want to train a new model, my files are located in "/home/ubuntu/wav/" as you can see in the log above.
do I need anything else to run preprocess.py correctly?

**Comment by fatchord** [comment]
Ok, I'll add an option to ignore TTS training - that way it won't look for the .csv file for accompanying text.

**Comment by buscon** [comment]
great, thank you!

**Comment by buscon** [comment]
is there an easy way to ignore the TTS training for now?

**Comment by fatchord** [comment]
comment out these lines in preprocees.py


    text_dict = ljspeech(path)

    with open(f'{paths.data}text_dict.pkl', 'wb') as f:
        pickle.dump(text_dict, f)

**Comment by buscon** [comment]
great, thanks!
Now the preprocess worked out and I started the train.

Where does the information of preprocess and the training are stored?

**Comment by fatchord** [comment]
There is now an ignore_tts option in the hparams.py file. 

Have a look in the WaveRNN/data/ folder for output data

**Comment by pleaseehlp** [comment]
text_dict = ljspeech(path)

with open(f'{paths.data}text_dict.pkl', 'wb') as f:
    pickle.dump(text_dict, f)
=============================
i commented the above out in preprocess.py. then the following happened

D:\projects\anacanda-voice-project\WaveRNN-master\WaveRNN-master>python preproce
ss.py --path witch-wife_2010_librivox
  File "preprocess.py", line 77
    n_workers = max(1, args.num_workers)
            ^
IndentationError: expected an indented block
-----------------------------------------------------------
when I corrected the above and ran this again:

python preprocess.py --path witch-wife_2010_librivox 

 ran the above line and the the whole program crashed. I can't seemed to copy the error after this since it crashed. i spend about 2 days trying to get this up and running.
