### ISSUE TITLE
Slow inference time?

### ISSUE THREAD

**Issue by jbecke** [fatchord/WaveRNN#47]
Thanks for this great implementation @fatchord! On a P100 I can generate only about 1600 samples/second i.e. much slower than real time. Is this expected or have I done something wrong?

It looks like this implementation is using 10 res blocks so maybe this is expected? Is there any way to make it 4x real time like the WaveRNN paper does? 

Note I am talking only about the vocoder, not the tacotron part (i.e. mel spectrogram -> wav)

**Comment by fatchord** [comment]
@jbecke Thank you for your kind words. Have you tried the batched inference mode with WaveRNN? That should be around realtime on a decent GPU (note that audio quality suffers a little bit - play around with target and overlaps settings if you're interested in tinkering with it).

You can change the default setting for it in hparams.voc_gen_batched.

**Comment by jbecke** [comment]
Thanks! But unfortunately, in my use-case I do not have the whole spectrogram before vocoding i.e. chunking and vocoding the spectrogram in parallel will not work. In my application the target spectrogram is being synthesized in real time, then I need to vocode that in real time as well. 

I suppose I should implement and train the reference WaveRNN instead of this modified model? Or do you think FFTNet would be better?

**Comment by fatchord** [comment]
@jbecke Well it's up to you I guess. All I'll say is that the spectrogram generation + wavernn vocoding in this repo is pretty damn fast and combined is often faster than realtime on my trusty old 1080GTX. I'm just wondering - why are you chunking the spectrogram in your application? I've found tacotron models to be pretty fast at generating output. 

I haven't had great results with the exact model described in the WaveRNN paper. Keep in mind though that that model was incomplete since they didn't describe the conditioning network in any detail. Other open source attempts at recreating it haven't convinced me either from a sound quality point of view - it'll work ok on ljspeech but sound terrible on lower register male voices.

**Comment by jbecke** [comment]
I'm working on real-time voice conversion. So it's not that I'm chunking the spectrogram but that inherently it is impossible to have the whole spectrogram (at time t only have spectrogram for [0,t]). Thanks for your advice! I'm going to try throwing a couple V100s at the issue and see if I can replicate their results...

**Comment by peter05010402** [comment]
@fatchord Hi friend， Thank you share the good job!
On my P100 GPU, run    python3 gen_tacotron.py --input_text "welcome to newzealand",
It cost 11s to generate.
How could I reduce the generate time?

**Comment by MorganCZY** [comment]
@jbecke Hi, may I ask what method or framework do you use to implement real-time voice conversion?
