### ISSUE TITLE
Would you consider train stop token in wav generation

### ISSUE THREAD

**Issue by begeekmyfriend** [fatchord/WaveRNN#74]
Just as T2 did, we might use a linear projection to produce a stop token for each output of WaveRNN. And therefore we can use the stop token to determine the actual length of the generated wav rather than use fade out factor to eliminate the redundant evaluation.

**Comment by fatchord** [comment]
@begeekmyfriend Currently the model just predicts empty frames to stop itself. The fadeout in WaveRNN is there because the MOL version generates noise from empty frames. I think the best solution to this is to add a tiny bit of empty frame = silence data when training WaveRNN. 

I'm not convinced a stop network is 100% necessary although it is trivial to implement so we'll see.

**Comment by begeekmyfriend** [comment]
All right. Closing this issue. Feel free to reopen it.
